site_name: LTA GIS Workshop Apr 2022 -- Lab Exercises
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Lab 1:
      - index.md
  - Lab 4:
      - lab4.md
